//
//  Consts.h
//  TEP Project
//
//  Created by Michał Raszczuk on 30/12/2019.
//  Copyright © 2019 Michał Raszczuk. All rights reserved.
//

#ifndef Consts_h
#define Consts_h

//errors
#define NO_ERROR 0
#define NULL_SOLUTION_POINTER_ERROR 1
#define WRONG_SOLUTION_SIZE_ERROR 2

#define WRONG_ARGUMENT_ERROR 3

#define FILE_NOT_CLOSED 4;

//default values
#define DEFAULT_DIM_X 2
#define DEFAULT_DIM_Y 2

#define DEFAULT_TABLE_SIZE 5

#define DEFAULT_MSCN_PROBLEM_M_COUNT 3
#define DEFAULT_MSCN_PROBLEM_F_COUNT 3
#define DEFAULT_MSCN_PROBLEM_S_COUNT 3
#define DEFAULT_MSCN_PROBLEM_D_COUNT 3

#define MIN_VALUE_MSCN_MIN_MAX_TABLE 0
#define MAX_VALUE_MSCN_MIN_MAX_TABLE 1

#define DEFAULT_MIN_RANGE_VALUE 0
#define DEFAULT_MAX_RANGE_VALUE 1

#define DEFAULT_DOUBLE_NUMBER 0.0

#define DEFAULT_MSCN_S_RANDOM_MIN_VALUE 0
#define DEFAULT_MSCN_S_RANDOM_MAX_VALUE 50

#define DEFAULT_MSCN_U_RANDOM_MIN_VALUE 0
#define DEFAULT_MSCN_U_RANDOM_MAX_VALUE 50

#define DEFAULT_MSCN_C_RANDOM_MIN_VALUE 0
#define DEFAULT_MSCN_C_RANDOM_MAX_VALUE 50

#define DEFAULT_MSCN_P_RANDOM_MIN_VALUE 0
#define DEFAULT_MSCN_P_RANDOM_MAX_VALUE 50


#endif /* Consts_h */
